"""Regenerate bundled NYSE sessions after calendar updates (including special closures)."""
import json
from pathlib import Path
import pandas_market_calendars as mcal

start, end = "2025-01-01", "2035-12-31"
schedule = mcal.get_calendar("NYSE").schedule(start_date=start, end_date=end)
sessions = {str(day.date()): [row.market_open.isoformat(), row.market_close.isoformat()] for day, row in schedule.iterrows()}
target = Path(__file__).parents[1] / "frontend/src/nyseSessions.ts"
target.write_text(
    "// Generated by scripts/generate_market_calendar.py using the backend NYSE calendar.\n"
    f"export const calendarStart = '{start}', calendarEnd = '{end}';\n"
    "export const sessions: Record<string, [string, string]> = " + json.dumps(sessions, separators=(",", ":")) + ";\n",
    encoding="utf-8",
)
